# Site settings
title: GoFree Robot
SEOTitle: GoFree Robot
header-img: img/home-bg.jpg
email: like1997@mail.ustc.edu.cn
description: "May Your Heart Be The Map"
keyword: ""
url: "http://gofreerobot.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

math:
  # Default (true) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in Front-matter.
  # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: true
  # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
  mathjax:
    enable: true
    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem: false

# SNS settings
RSS: false
# weibo_username:   
github_username: ahlike
#zhihu_username:     
#twitter_username:  
#facebook_username:  



# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
gems: [jekyll-paginate]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: GoFree Robot
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: d59d067e8500ddc9aafddb11c2cdc1ab
# Google Analytics
ga_track_id: 'UA-75516959-1'            # Format: UA-xxxxxx-xx
ga_domain: gofreerobot.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "USTC Like"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "CSDN 秃头队长",
        href: "https://blog.csdn.net/qq_39266065"
    },
    {
        title: "知乎 浮城大亨",
        href: "https://www.zhihu.com/people/yu-you-wei-42"
    }
]
